docker-build:
  image: docker:cli
  stage: build
  services:
    - name: docker:27.3.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker context create builder
    - docker buildx create builder --use
    - |
      [ "$CI_DEFAULT_BRANCH" == "$CI_COMMIT_BRANCH" ] && TAGS="--tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA" 
      [ -z "$CI_COMMIT_TAG" ] && TAGS="--tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest"
    - docker buildx build --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/cache --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/cache --push --platform linux/arm64/v8,linux/amd64 $TAGS .
