include:
  - component: $CI_SERVER_FQDN/components/go/format@1.0.0
  - component: $CI_SERVER_FQDN/components/go/test@1.0.0

stages: ["format", "test", "build", "deploy"]

container-build:
  image:
    name: quay.io/buildah/stable
  stage: build
  script:
    - dnf install -y qemu-user-static
    - buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - buildah build
      --layers
      --cache-from $CI_REGISTRY_IMAGE/cache
      --cache-to $CI_REGISTRY_IMAGE/cache
      --jobs 2
      --platform=linux/amd64,linux/arm64
      --manifest "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
      .
    - buildah manifest push --all "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"

container-copy:
  stage: build
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - crane copy "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"  "$CI_REGISTRY_IMAGE:test"
    - crane copy "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"  "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
    - crane copy "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"  "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_TAG
