name: Build Container

on: push

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Build and push container image
        uses: https://codeberg.org/maltech/buildah-action@v0.1.2
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          username: ${{ secrets.FORGEJO_USERNAME }}
          token: ${{ secrets.FORGEJO_PASSWORD }}
