name: Build Go

permissions: {} # no need any permissions

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ inputs.groupSuffix }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: docker
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: https://data.forgejo.org/actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Go Generate
        run: go generate ./... && git diff --exit-code

      - name: Go Build
        run: go build -o=/dev/null ./...

      - name: Go Vet
        run: go vet ./...

      - name: Go Compile Tests
        run: go test -exec=/bin/true ./...

      - name: Go Test
        run: go test -v -shuffle=on -race -count=1 -coverprofile=coverage.txt ./...

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=^$ -bench=. -benchtime=1x ./...

      #- name: Upload Coverage
      #  if: ${{ !inputs.skipTests }}
      #  uses: codecov/codecov-action@v4
      #  continue-on-error: true
      #  with:
      #    token: ${{secrets.CODECOV_TOKEN}}
      #    file: ./coverage.txt
      #    fail_ci_if_error: false
